### ISSUE TITLE
Show real progress pie on the project management screen

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/translationRecorder#498]
## User Story

As a facilitator I would like to see progress ob a project being displayed on the Book and Chapter level of the project management screens to reflect the work done and left to be done.

**Comment by vleong2332** [comment]
Progress pie now works.

However, it's slow due to the calculation that utilizes JSON parsing to get the number of total chapters in a project and total units in a chapter.

Optimizing this requires some feedback from the PO about custom versification and whether or not that will change the number of chapters in a book, and of units in a chapter.

**Comment by vleong2332** [comment]
By reviewing the workflow and removing redundant operations, we're able to improve the Chapter List Activity startup time significantly. I'm moving this for review.
