### ISSUE TITLE
As a narrator I want to be able to load an existing recording into the recording panel for review and editing.

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/translationRecorder#60]

**Comment by jsarabia1247** [comment]
- [ ] Investigate how the waveform is being drawn in Ringdroid (8)

- [ ] Either implement Ringdroid's method for waveform drawing or save visualization files so that loading an existing recording can happen in a reasonable amount of time (21)

- [ ] Split the current Recording Screen into two screens, one for recording and one for playback (8)
