### ISSUE TITLE
translationRecorder crashes if you select the project management icon instead of the microphone icon

### ISSUE THREAD

**Issue by sea-liesch** [WycliffeAssociates/translationRecorder#812]
We installed tRecorder on 4 different devices.  3 of them exhibited the same issue.  If you opened tRecorder and selected the project management icon in the smaller blue rectangular box, the app crashed straight away.   If you select the microphone icon in the larger red box, we were able to follow through and  actually do a recording.  Once  a recording was made, we could go back to the project management icon and open the project.  Once the project was deleted, the problem was not reproducible.

Failed on:
Samsung s7  Android v 6.0.1
Asus ZenPad s 8.0 Z580ca Android v 5.0.0
 Lenovo TAB 2 A10-70F Android v 5.0.1

Works as expected on: 
Asus Chromebook  C100P  running version 55.0.2883.105 with the Playstore enabled

**Comment by jsarabia1247** [comment]
Thanks for the feedback,

I was able to track down the issue through the crash reports, and pushed out an update (1.0.3) that should fix it. It had to do with first time use of the app producing a null value instead of an empty list of files when checking for which projects exist if a recording had not been first created..

**Comment by Redmayspecial** [comment]
Fixed in current versions
